name: cronjob

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run python script
        run: python hello.py
